name: Learn Workflow Triggers

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
env:
  BUILD_SUCCESS_MESSAGE: "Build succeeded"
 
jobs:  
 pasta-complete: 
    name: Pasta Complete
    runs-on: macOS-latest
    needs: cook-pasta
    steps:
      - run: echo ğŸ˜ nice
 cook-pasta:
  name: Cook Pasta
  runs-on: macOS-latest
  steps: 
    - run: echo ğŸš°
    - run: sleep 2
    - run: echo ğŸ‘©â€ğŸ³ ğŸ¥˜
    - run: echo "cooking..."
    - run: sleep 2
    - run: echo "done! ğŸ"
   
