name: Hello World

on:
 push:
   branches: 
    [master, develop]
    
jobs: 
  say-hello-world:
    name: "Say Hello World"
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ ${{job.name}} is starting!"
      - run: echo "Hello World"
      - run: echo 
      - run: sleep 2
      - run: echo "ğŸ This job's status is ${{ job.status }}."
